# Environments
ENV:
  DEVICE: cuda     # cuda, cpu
  GPU_NUM: 0

# Media
MEDIA:
  SOURCE: 0
  OPT_AUTO: True
  FOURCC: "MJPG"
  WIDTH: 1280
  HEIGHT: 720
  FPS: 30
  REALTIME: False
  BGR: True
  ENABLE_PARAM: False
  CV_PARAM:
    - cv2.CAP_PROP_AUTO_EXPOSURE: 1
    - cv2.CAP_PROP_BRIGHTNESS: 128
    - cv2.CAP_PROP_EXPOSURE: 50

# Object Detector
DET:
  MODEL_TYPE: yolov11
  DET_MODEL_PATH: './weights/yolov11/yolo11m.pt'
  HALF: False
  CONF_THRES: 0.5
  OBJ_CLASSES: [0]
  YOLO:
    IMG_SIZE: 640
    NMS_IOU: 0.45
    AGNOSTIC_NMS: True
    MAX_DET: 100


# Object Tracker
TRACK:
  TRACK_MODEL_TYPE: "bytetrack"  # 'sort', 'deepsort', 'bytetrack'
#  TRACK_USE_ENCODER: false
#  TRACK_MODEL_PATH: "./weights/osnet_x0_25_market1501.pt"
#  TRACK_HALF: false
  PERSON:
    MAX_BBOX_HISTORY: 100
    TIMEOUT_SEC: 30
  SORT:
    MAX_AGE: 1
    MIN_HITS: 3
    IOU_THRES: 0.3
  DEEPSORT:
    MODEL_PATH: "./weights/deepsort/ckpt.t7"
    MAX_DIST: 0.2
    NN_BUDGET: 100
    USE_CUDA: True
  BYTETRACK:
    TRACK_THRES: 0.6
    TRACK_BUFFER: 30
    MATCH_THRES: 0.9
    FRAME_RATE: 30


# =========================
# Logging Configuration
# =========================
LOG:
  # Specify the logging level. Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  LOG_LEVEL: 'debug'

  # Name of the logger. Useful when using multiple loggers.
  LOGGER_NAME: "tracker"

  # Enable or disable logging to the console. true/false
  CONSOLE_LOG: true

  # Interval for console log during video analysis
  CONSOLE_LOG_INTERVAL: 100

  # Enable or disable saving logs to a file. true/false
  FILE_LOG: true

  # Directory path for saving log files.
  FILE_LOG_DIR: './log/'

  # Maximum number of backup files for log rotation.
  FILE_LOG_COUNTER: 30

  # Log rotation frequency. Options: 'S'(seconds), 'M'(minutes), 'H'(hours), 'D'(days)
  FILE_LOG_ROTATE_TIME: "D"

  # Interval for log rotation, used with FILE_LOG_ROTATE_TIME.
  FILE_LOG_ROTATE_INTERVAL: 1
